name: Lint

on:
  pull_request:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install flake8 black  # Add Black to the installation command

      - name: Run Flake8 and Black
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          black --check .
